Add Win validierung
MarcRaeder/4Gewinnt pull request #5
Opened 2022-11-08 07:21 UTC by MarcRaeder

Add Win validierung

2022-11-08 08:13 UTC, DevBastiS approved these changes

2022-11-08 08:13 UTC, DevBastiS commented on StatusValidator.py
> +        verticalWin = StatusValidator.verticalWin(board, player, row)
The third parameter here is "row". In the function itself it is called column. Is this correct?

2022-11-08 08:13 UTC, DevBastiS commented on MainGame.py
> +        if self.roundNumber > 21:
21 is a "magic number". Move it to a constant and give it a speaking name.

2022-11-10 11:45 UTC, stefanluth requested changes

2022-11-10 11:45 UTC, stefanluth commented on MainGame.py
> +    def Turn(self, player: Player) -> None or Player:
`None or Player` is not a valid type :) Use [Optional](https://docs.python.org/3/library/typing.html#typing.Optional) or [Unions](https://docs.python.org/3/library/typing.html#typing.Union) instead

2022-11-10 11:45 UTC, stefanluth commented on MainGame.py
>              if isvalidTurn:
```suggestion
            if isValidTurn:
```

2022-11-10 11:45 UTC, stefanluth commented on MainGame.py
> +    def Round(self) -> None or Player:
See above :)

2022-11-10 11:45 UTC, stefanluth commented on MainGame.py
> +        maxRounds = 21
Move this to be a class variable or global constant :)

2022-11-10 11:45 UTC, stefanluth commented on MainGame.py
> +            return winner
It would make more sense to move the "is player the winner?" variable to the `Player` class

2022-11-10 11:45 UTC, stefanluth commented on StatusValidator.py
> +    def isWin(board: Board, player: Player, column: int) -> bool:
The first parameter should be `self`

2022-11-14 13:05 UTC, stefanluth requested changes

2022-11-14 13:05 UTC, stefanluth commented on MainGame.py
> +                return player
This always returns `player`

2022-11-14 13:05 UTC, stefanluth commented on MainGame.py
> +                return player
This whole block also always returns `player`

2022-11-14 13:05 UTC, stefanluth commented on MainGame.py
> +        winner: Player = self.Turn(self.playerOne)
```suggestion
        player = self.Turn(self.playerOne)
```
Because the method returns `Player`, the type of `winner` is inferred. Also, `player` is a more fitting name :)

2022-11-14 13:05 UTC, stefanluth commented on MainGame.py
> +    def Turn(self, player: Player) -> Optional[Player]:
```suggestion
    def Turn(self, player: Player) -> Player:
```

The method always returns a `Player`

2022-11-14 13:05 UTC, stefanluth commented on MainGame.py
> +        winner: Player
You define `winner` to be `Player` here, but don't initialize it with an instance of `Player`, which means it is `None`.

2022-11-14 13:05 UTC, stefanluth commented on StatusValidator.py
> +    def horizontalWin(board: Board, player: Player) -> bool:
All methods in a class should have `self` as first parameter. (Unless they're `staticmethods` or `classmethods`.)

2022-11-14 13:32 UTC, stefanluth approved these changes

2022-11-14 13:33 UTC, merged