Spielablauf finalisieren
MarcRaeder/4Gewinnt pull request #6
Opened 2022-11-14 13:39 UTC by MarcRaeder

add restart function

2022-11-14 13:41 UTC, stefanluth requested changes

2022-11-14 13:41 UTC, stefanluth commented on 4Gewinnt.py
> -    game = MainGame()
Pythonic snake_case or stay with the current camelCase :)

2022-11-14 13:41 UTC, stefanluth commented on MainGame.py
> +
```suggestion
        if player.name == "":
```

Random changes :D

2022-11-14 13:41 UTC, stefanluth commented on Player.py
> +        self.name = None
```suggestion
        self.name: str | None = None
```

2022-11-15 09:02 UTC, stefanluth approved these changes

2022-11-15 09:03 UTC, MKrips approved these changes

2022-11-15 09:41 UTC, DevBastiS approved these changes

2022-11-15 12:32 UTC, merged